import animations from "@axieinfinity/mixer/dist/data/axie-2d-v3-stuff-animations.json";

export const animationListData: string[] = animations.items.header
  .map((obj: any) => obj.name)
  .filter((obj: any) => obj.substring(0, 10) !== "action/mix");

  //from 0 to 8 action
  //from 9 to 16 activity
  //from 17 to 30 attack
  //from 31 to 36 defesese
  //37 and 38 battle

  export const animationList: string[] = [
    "action/move-back",
    "action/move-forward",
    // "action/idle/normal",
    "action/idle/random-01",
    "action/idle/random-02",
    "action/idle/random-03",
    "action/idle/random-04",
    // "action/idle/random-05",
    "action/run",
    "draft/run-origin",
    "activity/appear",
    // "activity/bath",
    "activity/eat-bite",
    "activity/eat-chew",
    "activity/entrance",
    "activity/sleep",
    "activity/victory-pose-back-flip",
    "activity/evolve",
    "activity/prepare",
    "attack/ranged/cast-fly",
    "attack/ranged/cast-high",
    "attack/ranged/cast-low",
    "attack/ranged/cast-multi",
    "attack/ranged/cast-tail",
    "attack/melee/shrimp",
    "attack/melee/tail-multi-slap",
    "attack/melee/tail-roll",
    "attack/melee/tail-smash",
    "attack/melee/tail-thrash",
    "attack/melee/horn-gore",
    "attack/melee/mouth-bite",
    "attack/melee/multi-attack",
    "attack/melee/normal-attack",
    "defense/evade",
    "defense/hit-by-normal",
    "defense/hit-by-normal-crit",
    "defense/hit-by-normal-dramatic",
    "defense/hit-by-ranged-attack",
    "defense/hit-with-shield",
    "battle/get-buff",
    "battle/get-debuff",
]  

export const animationListNames: string[] = [
  "Move back",
  "Move forward",
  "Random 01",
  "Random 02",
  "Random 03",
  "Random 04",
  "Run",
  "Run Origins",
  "Appear",
  "Eat bite",
  "Eat chew",
  "Entrance",
  "Sleep",
  "Victory Back flip",
  "Evolve",
  "Prepare",
  "Cast fly",
  "Cast high",
  "Cast low",
  "Cast multi",
  "Cast tail",
  "Shrimp",
  "Tailmulti slap",
  "Tailroll",
  "Tailsmash",
  "Tailthrash",
  "Horn gore",
  "Mouth bite",
  "Multi attack",
  "Normal attack",
  "Evade",
  "Hit normal",
  "Hit normal crit",
  "Hit normal dramatic",
  "Hit by ranged",
  "Hit with shield",
  "Get buff",
  "Get debuff",
]  